version: 2
updates:
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly

  - package-ecosystem: gradle
    directory: /Android/src
    schedule:
      interval: weekly
    allow:
      - dependency-name: "com.google.ai.edge.litertlm:*"
